language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

env:
  global:
  - CMAKE_CXX_STANDARD=14
install:
  - echo Lang:$LANG. OS:$TRAVIS_OS_NAME. CC:$CC.
  - uname -a
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      if [ -z `brew list | grep cmake` ]; then brew install cmake; fi
      brew outdated cmake || brew upgrade cmake
      #if [ -z `which ninja` ]; then brew install ninja; fi
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install -y cmake ninja
    fi
  - ./ci/lua_local.sh
  
script:
  - ./ci/build.sh

notifications:
  email: false


